name: Docker Image CI

on:
  push:
    branches: [ "cursor/build-local-ai-video-generation-system-5d52" ]
  pull_request:
    branches: [ "cursor/build-local-ai-video-generation-system-5d52" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
